### ISSUE TITLE
Can't update default maven-public repository

### ISSUE THREAD

**Issue by alexconlin** [datadrivers/terraform-provider-nexus#107]
A standard install of nexus-oss comes with a default maven2 group repository "maven-public".

I attempted to add a repository to this group using the provider with a configuration like this:

```
resource "nexus_repository" "maven_public" {
  name   = "maven-public"
  format = "maven2"
  type   = "group"
  online = true

  group {
    member_names = [
      "maven-releases",
      "maven-snapshots",
      "maven-central",
      "my-other-maven2-repo"
    ]
  }

  http_client {
    blocked = false
  }

  storage {
    blob_store_name                = "default"
    strict_content_type_validation = true
  }
}
```

and received the following error:

`could not create repository 'maven-public': HTTP: 400, "Cannot index record #17:8: found duplicated key 'maven-public' in index 'repository_repository_name_idx' previously assigned to the record #17:3
`

Looking at the code in `resource_repository.go` I wonder if this is because there is no setup for reading and writing maven2 repos?

**Comment by anmoel** [comment]
hi @alexconlin,

thanks for your contribution.
The error message is an expected behavior, because the the repository already exists.

To meet your expectations we have to install an update process for existing repositories.
So i will change the tag from bug to enhancement and add this feature to our implementation list.

it would be nice if you can support.

thanks in advance and kind regards
André
