### ISSUE TITLE
Error: could not create repository 

### ISSUE THREAD

**Issue by chewrocca** [datadrivers/terraform-provider-nexus#173]
**Describe the bug**
Terraform doesn't appear to create a repository.  It complains about ID which I think is "read-only".

**To Reproduce**
added the following config:

```sh
resource "nexus_repository" "docker-private" {
  format = "docker"
  name   = "docker-private"
  online = true
  type   = "proxy"

  http_client {
    auto_block = true
    blocked    = false

    connection {
      use_trust_store = true
    }

  }

  negative_cache {
    enabled = true
    ttl     = 60
  }

  proxy {
    content_max_age  = 120
    metadata_max_age = 120
    remote_url       = var.nexus_url
  }

  docker {
    force_basic_auth = false
    http_port        = 8083
    https_port       = 0
    v1enabled        = false
  }

  docker_proxy {
    index_type = "REGISTRY"
  }

  storage {
    blob_store_name                = nexus_blobstore_file.portworxblob.name
    strict_content_type_validation = true
  }
}
```

did tf plan and apply and it errored out with:

```sh
│ Error: could not create repository 'docker-private': HTTP: 400, [ {
│   "id" : "PARAMETER timeout",
│   "message" : "must be greater than or equal to 1"
│ } ]
│ 
│   with module.nexus_repos_bos.nexus_repository.docker-private,
│   on modules/nexus-repos-proxy/main.tf line 257, in resource "nexus_repository" "docker-private":
│  257: resource "nexus_repository" "docker-private" {
│ 
```

**Expected behavior**
I wasn't expecting it to error out.

**Comment by anmoel** [comment]
hi @chewrocca 

thanks for your report.
The problem itself is due to the missing field with the id "timeout". This value must be defined in the connection block of the http client.

Are you using the latest version from the provider and if so, is this error due to the update or is it a new resource?
We have changed the backend client and we don't have tests for all possible repository types with all options, as the resource nexus_repository is difficult to maintain and is therefore deprecated.
We are working on dividing the repository resource into separate resources.

kind regards and thanks in advance
André

**Comment by chewrocca** [comment]
thanks, i was just testing that out.  sounded like that was an optional field.  

closing issue.

**Comment by anmoel** [comment]
hi @chewrocca,

yes, this timeout field must be optional, because some repository types have this field as optional value and some like docker requires this value. that's the cause we decide to split up the resource nexus_repository.

regards André
