### ISSUE TITLE
Proxy and Remote repository types should not allow `write_policy` attribute under `storage`

### ISSUE THREAD

**Issue by c4rlier** [datadrivers/terraform-provider-nexus#29]
Hi,
one more submission. As per Nexus' API Proxy and Remote repository types should not allow `write_policy` attribute under `storage`.

**Comment by Nosmoht** [comment]
Hi @c4rlier ,

thanks for the hint. I'll check how to implement that.

**Comment by Nosmoht** [comment]
Implementation is already done, but i found an issue for proxy repositories of format `apt` and `docker`.

https://issues.sonatype.org/browse/NEXUS-24502

**Comment by EugenMayer** [comment]
If `write_policy` is set nevertheless, it leads to no errors but rather is simply not applied and will trigger an update on each new apply (since it cannot be applied). Not critical in this sense, but was surprising to me until i found this issue and it became obvious that it should not be set at all

**Comment by anmoel** [comment]
we split the repository resource in seperated resources for each repo type and format. please use the new resources. i close this issue.
